EmployeeApplication/Models/Emp.cs
using System;
using System.Collections.Generic;

namespace EmployeeApplication.Models
{
    public partial class Emp
    {
        public int Id { get; set; }
        public string? Fname { get; set; }
        public string? Lname { get; set; }
        public DateTime? Dob { get; set; }
        public int? Contact { get; set; }
        public string? Email { get; set; }
        public string? Password { get; set; }
        public byte[]? Photo { get; set; }
      
        public int? StateId { get; set; }
        public virtual State? State { get; set; }
    
        
    }
}

EmployeeApplication/Controllers/EmpController.cs
using EmployeeApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace EmployeeApplication.Controllers
{
    public class EmpController : Controller
    {
        private readonly employeeContext _context;

        public EmpController(employeeContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var employee = _context.Emps.Include(e => e.State).Include(e => e.State.Cities).ToList();
            return View(employee);
        }



        public IActionResult Create()
        {
           ViewBag.States = new SelectList (_context.States, "StateId","StateName");
           ViewBag.Cities = new SelectList(new List<City>(), "CityId", "CityName"); // Empty list initially

            return View();
        }

        [HttpPost]
        public IActionResult Create(Emp obj, IFormFile photo)
        {
            if (ModelState.IsValid)
            {
                if (photo != null && photo.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        photo.CopyTo(memoryStream);
                        obj.Photo = memoryStream.ToArray();
                    }
                }

                
                _context.Emps.Add(obj);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.States = new SelectList(_context.States, "StateId", "StateName");
            return View();
        }


       



        public IActionResult Edit(int id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Emp? EmpFromDb = _context.Emps.FirstOrDefault(c => c.Id == id); ;


            if (EmpFromDb == null)
            {
                return NotFound();
            }
            ViewBag.States = new SelectList(_context.States, "StateId", "StateName");
            return View(EmpFromDb);
        }

        [HttpPost]
        public IActionResult Edit(Emp obj, IFormFile photo)
        {
            if (ModelState.IsValid)
            {
                if (photo != null && photo.Length > 0)
                {
                    using (var memoryStream = new MemoryStream())
                    {
                        photo.CopyTo(memoryStream);
                        obj.Photo = memoryStream.ToArray();
                    }
                }
                _context.Emps.Update(obj);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.States = new SelectList(_context.States, "StateId", "StateName");
            return View();
        }


        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Emp? EmpFromDb = _context.Emps.FirstOrDefault(c => c.Id == id);
            if (EmpFromDb == null)
            {
                return NotFound();
            }
            return View(EmpFromDb);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            Emp obj = _context.Emps.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _context.Emps.Remove(obj);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

EmployeeApplication/Views/Emp/Create.cshtml
@model EmployeeApplication.Models.Emp

@{
    ViewData["Title"] = "Create Employee";
}

<h1>Create Employee</h1>

<form asp-action="Create" method="post" enctype="multipart/form-data">
    <div>
        <label asp-for="Fname">First Name:</label>
        <input asp-for="Fname" class="form-control" />
        <span asp-validation-for="Fname" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Lname">Last Name:</label>
        <input asp-for="Lname" class="form-control" />
        <span asp-validation-for="Lname" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Dob">Date of Birth:</label>
        <input asp-for="Dob" class="form-control" type="date" />
        <span asp-validation-for="Dob" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Contact">Contact:</label>
        <input asp-for="Contact" class="form-control" />
        <span asp-validation-for="Contact" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Email">Email:</label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="Photo">Photo:</label>
        <input type="file" asp-for="Photo" class="form-control-file" />
        <span asp-validation-for="Photo" class="text-danger"></span>
    </div>
    <div>
        <label asp-for="StateId">State:</label>
        <select asp-for="StateId" asp-items="ViewBag.States" class="form-control">
            <option value="">Select State</option>
        </select>
        <span asp-validation-for="StateId" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>

EmployeeApplication/Views/Emp/Delete.cshtml
@model Emp

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Employee</h2>
        </div>
        <div class="mb-3">
            <label>First Name</label>
            <input asp-for="Fname" type="text" class="form-control" />
            <span asp-validation-for="Fname" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Last Name</label>
            <input asp-for="Lname" type="text" class="form-control" />
            <span asp-validation-for="Lname" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>DOB</label>
            <input asp-for="Dob" type="date" class="form-control" />
            <span asp-validation-for="Dob" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Contact</label>
            <input asp-for="Contact" type="number" class="form-control" />
            <span asp-validation-for="Contact" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Email</label>
            <input asp-for="Email" type="email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Photo</label>
            <input asp-for="Photo" type="image" class="form-control" />
            <span asp-validation-for="Photo" class="text-danger"></span>
        </div>
        <br />
        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-danger form-control">Delete</button>
            </div>
            <div class="col-6">
                <a asp-controller="Emp" asp-action="Index" class="btn btn-outline-secondary form-control">Back T List</a>
            </div>
        </div>


    </div>
</form>

EmployeeApplication/Views/Emp/Edit.cshtml
@model Emp

@{
    ViewData["Title"] = "Edit Employee";
}

<form asp-action="Edit" method="post" enctype="multipart/form-data">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Employee</h2>
        </div>
        <div class="mb-3">
            <label>First Name</label>
            <input asp-for="Fname" type="text" class="form-control" />
            <span asp-validation-for="Fname" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Last Name</label>
            <input asp-for="Lname" type="text" class="form-control" />
            <span asp-validation-for="Lname" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>DOB</label>
            <input asp-for="Dob" type="date" class="form-control" />
            <span asp-validation-for="Dob" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Contact</label>
            <input asp-for="Contact" type="number" class="form-control" />
            <span asp-validation-for="Contact" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Email</label>
            <input asp-for="Email" type="email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>Photo</label>
            <input asp-for="Photo" type="file" class="form-control" />
            <span asp-validation-for="Photo" class="text-danger"></span>
        </div>

        <div>
            <label asp-for="StateId">State:</label>
            <select asp-for="StateId" asp-items="ViewBag.States" class="form-control">
                <option value="">Select State</option>
            </select>
            <span asp-validation-for="StateId" class="text-danger"></span>
        </div>

        <br />
        <div class="row">
            <div class="col-6">
                <button type="submit" class="btn btn-primary form-control">Update</button>
            </div>
            <div class="col-6">
                <a asp-controller="Emp" asp-action="Index" class="btn btn-outline-secondary form-control">Back T0 List</a>
            </div>
        </div>


    </div>
</form>

EmployeeApplication/Views/Emp/Index.cshtml
@model List<Emp>

<div class="container">
    <div class="row pt-4 pb-3">
        <div class="col-6">
            <h2 class="text-primary">
                Employee list
            </h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Emp" asp-action="Create" class="btn btn-primary">
                Create New Employee
            </a>
        </div>
    </div>

    <br />
    <table class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>
                    Index
                </th>
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                </th>
                <th>
                    DOB
                </th>
                <th>
                    Contact
                </th>
                <th>
                    Email
                </th>
                <th>
                    State
                </th>
                <th>
                    Photo
                </th>
                <th>
                    EDIT
                </th>
                <th>
                    Delete
                </th>

            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td>@obj.Id</td>
                    <td>@obj.Fname</td>
                    <td>@obj.Lname</td>
                    <td>@obj.Dob</td>
                    <td>@obj.Contact</td>
                    <td>@obj.Email</td>
                    <td>@obj.State</td>
                    <td>
                        @if (obj.Photo != null && obj.Photo.Length > 0)
                        {
                            <img src="data:image;base64,@Convert.ToBase64String(obj.Photo)" alt="Employee Photo" class="img-fluid" />
                        }
                        else
                        {
                            <span>No Photo</span>
                        }
                    </td>

                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Emp" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary ">
                                Edit
                            </a>
                        </div>
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Emp" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger ">
                                Delete
                            </a>
                        </div>
                    </td>

                </tr>
            }
        </tbody>

    </table>
</div>